# Generated by Django 5.1.5 on 2025-02-10 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_about_booking_menuitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='date',
            new_name='da',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='email',
            new_name='em',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='guests',
            new_name='gu',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='name',
            new_name='nm',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='phone',
            new_name='ph',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='time',
            new_name='ti',
        ),
    ]
